# 使用 Debian 作为基础镜像
FROM debian:latest

# 更新系统并安装必要工具
RUN apt-get update && apt-get install -y \
    curl \
    git \
    gcc \
    g++ \
    cmake \
    make \
    libssl-dev \
    build-essential \
    ca-certificates \
    wget \
    unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 验证安装是否完成
RUN curl --version && git --version && gcc --version


# docker tag debian-tools leijmin/debian-tools:latest
# docker push leijmin/debian-tools:latest